sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

git:
  depth: 4

services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-cssource-freeplay --build-arg BUILDNODE=TravisCI ./linux
  - docker run -it --rm lacledeslan/gamesvr-cssource-freeplay ./ll-tests/gamesvr-cssource.sh

after_script:
  - docker images
